openSUSE/obs-build

- build-recipe-spec
If the --nocheck rpmbuild option is not supported, disable at least the
post build checks. This happens e.g. on SLE11.
> Fix --no-checks with older rpmbuild

- init_buildsystem
The readlink command substitution should be escaped. Otherwise we are getting the path in the host env instead of the chroot env.
> Fixing UTC symlink resolving when setting localtime

- build
- build-vm
- build-vm-docker
This change adds support for building inside lightweight Docker containers.
The following approach is used.
* Minimal busybox pre-built image is used
(downloaded from Docker Hub automatically on the first use).
* Docker container is started from this image.
* The container is configured with sys_admin capability granted
to allow second stage to mount "/proc" and "/sys".
* Build root is configured as a volume for this container, mounted at
"/mnt" directory inside the container.
* Second stage is started inside the container, chrooted in "/mnt" directory.
This convoluted approach is used for the following reasons.
* There's no way in Docker to mount container's root fs and populate it
(as with KVM build).
* You can only create containers from images, mount some host directories
to …
> Add initial support for building inside Docker containers.

- vc
In case vc created a new changelog file (via touch) but nothing got
added the empty file still remained. Since it's empty and the user
"aborted" creating one, it should get deleted.
> vc: create changelog file only in case of a change

- Build.pm
- build-recipe
- build-recipe-simpleimage
Simple image is a really simple way how to get rootfs tarball or
squashfs image. The main advantage over existing solution like kiwi is
that it is distribution independent and therefore any distribution
supported by obs can make use of it. Disadvantage is that it is simple
and basically just preconfigured tarball - no bootloader, no kernel.
Syntax is pretty simple, all you need is to create simpleimage file and
write what you want inside of it. Here is the simple example, all fields
are optional as is the %build section.
+----------------------------------+
| Name:           example          |
| Version:        1.0              |
| BuildRequire:   emacs            |
| #!BuildIgnore:  gcc-c++          |
|                                  |
| %build                           |
| passwd << …
> Support for simple images

- build-recipe-debootstrap
Debootstrap sometimes fails to setup packages, especially when the
dependencies aren't available. In this case it helpfully reports success
as it's exit code. Checking in the chroot if everything was left
unconfigured (and whether configuring that fails) detects these cases.
Also in such a case output the debootstrap log so it's easier to analyse
the problem.
> Double-check the debootstrap result

- build
This change fixes a bug intruduced when adding support for Docker.
LOGFILE should be initialised outside of vm regardless of vm type;
lxc and docker are special cases only inside vm.
Signed-off-by: Oleg Girko <ol@infoserver.lv>
> Fix logging for building with lxc and docker.

- build-recipe-dsc
From the lintian manpage:
EXIT STATUS
0   No policy violations or major errors detected.  (There may have
been warnings, though.)
1   Policy violations or major errors detected.
What policy is applied depends on the lintian profiles installed. See also
the "Lintian User's Manual" section on "Vendor Profiles":
https://lintian.debian.org/manual/section-2.5.html
> [backend] Allow lintian to break the build

- build-recipe-livebuild
live-build is producing different formats and additional metadata files.
> livebuild: Publish all build results including the metadata

- build-recipe-livebuild
If the upstream default "live-image" is used in OBS this will result in
the problem that build results overwrite each other in the repository.
Therefore lets provide a better default that is based on the recipe name.
> livebuild: Use recipefile basename as default live image name

- build
- build-vm
- build-vm-kvm
KVM build type need additional options.
For network: When build a commercial program, connect license server to get certification during the build.
For disk: cache disk is a shared disk, etc
There was no option to crash when I check.
> Additional support for kvm options of -net, -netdev, -device

- build-recipe-dsc
Include the changelog from the previous versions.
Add ~0 to use the current version in the changelog as well.
> dsc: Generate .changes files when building deb packages.

- build-recipe-dsc
Since commit 7e49410794f58316b3afaf5cf78c5ddc2fba9def the linitan call was
only covering the source Debian package. Since the build architecture is
gathered from the chroot it should be safe to use the changes file as
lintian input.
> debian: lintian should check generated binary and source package

- build
/var/run might point to the absolute path /run. Thus any commands
referencing $BUILD_ROOT/var/run are actually using the hosts /run
directory, whereas the "cd" tries to change to the nonexisting
/run/icecream directory and fails.
> use correct dir for creation of icecream env

- build-recipe-dsc
After the Debian transformer is run the *.dsc filename has changed. Therefore using the original *.dsc filename to deduce the changes file doesn't work always.
Fixes https://bugzilla.novell.com/show_bug.cgi?id=939398.
> Fix lintian changesfile

- build-recipe-dsc
To not modify the default behavior you need to set in the
control file this tag:
OBS-DCH-RELEASE: 1
Debtransform's DEBTRANSFORM-RELEASE can't be used for plain
Debian packages which doesn't require transformation.
> Set OBS release version even without debtransform

- build-recipe-livebuild
This allows us to do things in the livebuild_pre_run script based on what recipe we're building. For example, this could be used to vary the flags passed to `lb config`.
> Exported RECIPEFILE in build-recipe-livebuild

- spec_add_patch
Check if either the `--- ` filename starts with `a/` or the `+++ ` filename starts with `b/`, or either starts with a package name/version prefix. We have to check for either, because either of them could be `/dev/null` if a file is being added or deleted.
> Fix auto-detection of -p1 option to patch

- build-vm-kvm
In case we have /dev/hwrng present, use it as a backend device for
virtio-rng, fallback to /dev/random if hw is not there
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
> Add virtio-rng device to a VM

- build-vm-kvm
The generic device name is virtio-rng-device which works for all
platforms. virtio-rng-pci is a specific implementation attached
tot he PCI bus. Unfortunately, ARMv7 does not have a PCI bus, so
everything fails with:
No 'PCI' bus found for device 'virtio-rng-pci
> [armv7l] Unbreak random number device pass through

- build-vm-kvm
Even if /dev/hwrng exists there is no guarantee that a hw random device
exists.  If there is none it causes qemu to crash.
ERROR:backends/rng-random.c:47:entropy_available: assertion failed: (len != -1)
> build-vm-kvm: fix check for presence of hw random device

- build-vm-lxc
There are changes in `lxc-create` and `lxc-start` options in lxc 1.1:
* `lxc-create` now requires `-t` option to specify template;
* `lxc-start` now defaults to run in daemon mode, needs `-F` option to override.
> Update lxc-create and lxc-start options to work with newer lxc.

- build-vm
The VM creation was checking to see if a root image existed. In doing
so it skips subsequent changes to root image size.
> build-vm: Resize VM images

- mkbaselibs
When building packages on a private OBS instance occasionally I get the following error: "Can't use an undefined value as an ARRAY reference at /usr/lib/build/mkbaselibs". It happens if mkbaselibs gets empty packages (for instance *.debuginfo.rpm) among input arguments. It seems reasonable to skip such packages.
> Skip empty packages in mkbaselibs.

- build-recipe-spec
Preparational patch for some rpmlint changes. For example for kernel builds, rpmlint may take dozens of minutes until any output appears. To at least allow rpmlint to report progress, use tee to continuously pipe the log to stdout.
> Continuously output messages from rpmlint

- build-vm-lxc
Current LXC support works only for LXC 1.1. But LXC 1.1 does not work with OBS, so check now for the version and use 1.0 or 1.1 calls.
> [build] add support for LXC 1.0 and 1.1 parameter calls

- spec_add_patch
When a spec file has interleaved "Source" and "Patch" tags, the script
generated the wrong patchnumber (0) and put the patch after the last "Source"
line instead of after the last "Patch".
> Fix finding patch Number for certain spec files

- configs/debian.conf
Building some packages have dependencies related to auto testing.
We need initscripts to be run so that the startup scripts are correctly
linked for later use by postinst scripts from packages like cgmanager.
> Run initscripts during debian setup

- build-vm-kvm
On newer AArch64 platforms we need to use vGICv3, so use
gic-version=host which does auto-detection whether it is available
and uses it if there. The qemu check is needed to not break
older qemu versions (like those in SLE12).
> Set gic-version=host when provided by qemu-system-aarch64

- init_buildsystem
(This is a repost of the one unmerged commit from pull request #194 so it does not get lost.)
This reverts commit e2a3a2681057293a452938cb523783f8d88809e6.
That commit crippled progress reporting. Issue 1: It made the
"keeping" messages go away, but the progress indicator would still be
printed, so the commit only did half of the intent.
Issue 2: Since no newline was emitted (this was part of the "keeping"
message) and because stdout is line-buffered, the progress report
would only be sporadically emitted.
Furthermore, initializating a Debian root is slow compared to RPM, and
so there is a long time before any output is shown.
Show me my progress as it happens. Reinstate messages about kept
packages.
> Bring back printing progress per package when initializing build root

- build-vm-docker
path is ``/bin/chroot`` not ``/usr/sbin/chroot``. The ``/usr/sbin/``
directory exists but it is empty.
Tested with ``busybox:1.24`` and ``busybox:latest`` image.
> Fix the path to the chroot binary inside the busybox image. The

- build-pkg-arch
This small fix for Arch-package building. Arch Pacman goes forward faster than one can understand but with this small fix it should make it work foreseeable future (fixes also issue #222 ):
[    4s] [1/156] installing archlinux-keyring-20150605-1
[    4s] looking for conflicting packages...
[    4s] Packages (1) archlinux-keyring-20150605-1
[    4s] error: could not determine root mount point /
[    4s] error: not enough free disk space
[    4s] error: failed to commit transaction (not enough free disk space)
[    4s] Errors occurred, no packages were upgraded.
[    4s] exit ...
> Cannot create arch linux chroot

- build-recipe-debbuild
- build-recipe-spec
With the latest version of debbuild from Andreas Scherer, `debbuild` is now capable of limited configuration similar to RPM.
The debug stuff definitely has to be guarded out for now, as debbuild doesn't support making debug subpackages.
[The required version of debbuild has been submitted in OBS](https://build.opensuse.org/request/show/356636). The submitted version *must* be accepted before the code in this PR is deployed to build.o.o. However, after the PR is merged and a version of OBS-build with this code is deployed, the macros.obs-override file can be removed in the submitted version.
> Add support for debbuild's eval and .debmacros

- build-recipe-simpleimage
Solution: call cleanup_and_exit 1 if it fail
> Problem: simpleimage is built even if integration script fails

- build-recipe-kiwi
avoids recursive symlinks for repos
> clean topdir before kiwi build

- build-recipe-kiwi
In order to reuse single kiwi description for different architectures,
we must pass --add-profiles.
Here is example prjconf entry to control which profile to choose:
buildflags: kiwiprofile:profilename
Signed-off-by: Dinar Valeev <dvaleev@suse.com>
> Add KIWI profile support

- build-recipe-dsc
lintian couldn't find the .changes files due to the changed
filename which holds the OBS release suffix.
> Support lintian when OBS_DCH_RELEASE set

- build-vm-kvm
this makes it open the image files as root
and keeps using the file-descriptors after switching user
this is a follow-up on #245
> replace sudo usage by qemu's -runas

- Build/Deb.pm
Added a mapping for aarch64 architecture which is called arm64 in the Debian meta data.
> [build]: added DoD for aarch64 repositories on Debian

- build-vm-lxc
The new LXC 1.0.8 uses the same call parameters as LXC 1.1 and not as the old 1.0 branch.
> [build] add support for LXC 1.0.8

- build-pkg-deb
Required since --force all doesn't prevent that post/pre remove
scripts get called. Required since init_buildsystem is removing
package without honoring dependencies. (e.g. libexpt1 get removed
before python3 => python3 prerm scripts fail. Deinstallation fails.
osc build fails.)
> Add the dpkg way of noscripts removal

- build-vm-kvm
armv8l is the 32bit variant of aarch64, so we should use
the aarch64 case.
> Launch kvm properly for armv8l

- Build.pm
With that change, obs-build should be able to automatically configure for OpenSuSE Leap versions without the need of hardcoding the version string.
> Build.pm: add support for auto-detecting Leap versions.

- build-pkg-deb
Since dpkg 1.18.5 (Debian 9) --force-all implied --force-script-chrootless which will execute the maintainer scripts outside of the chroot even if they don't support that.
This fixes the installation of the chroot on Debian 9.
> Fix dpkg force all

- Build/Rpm.pm
Parametrized macros without curly braces consume all remaining arguments
until end-of-line.
Fixes evaluation of e.g "%define foo() %1", which caused "Use of
initialized value $line in ..." due to dereference of uncaputured $2.
> fix macro expansion for macros without curly braces

- Build/Arch.pm
Since PKGBUILD support architecture-specific sources, this is required for properly support some of them. Only 2 architectures supported officially.
> Add architecture-specific sources extract for Arch Linux

- configs/arch.conf
Without *lz4*, *pacman* can't work properely, making all builds fail.
> Adding needed pacman dependency

- Build/Arch.pm
Right now, the build system ignores them and this is not really nice.
This should do the trick (not sure, I'm learning Perl fixing stuff here almost).
> Don't forget of architecture-specific dependencies

- build-vm-docker
Sometimes we need to distinguish if we running build in a container.
/.dockerenv is a file exists in all images. Let's pretend we run a
propper image
Signed-off-by: Dinar Valeev <k0da@opensuse.org>
> create /.dockerenv in a $BUILD_ROOT

- createrepomddeps
@mlschroe please review
switching the mode of the filehandle to utf8 gets rid of the "wide characters in print" warnings.
> Prevent wide character warning

- build-vm-lxc
Recent SLES support LXC only via libvirt LXC driver.
This patch tests for lxc first and, if missing, virsh.
Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>
I tested this on SLES12SP1 and it is working nicely.
This patch also uses VM_MEMSIZE, which is not defined by OBS call. If this PR is accepted, I'll provide a trivial PR for obs-buildservice passing the --vm-memory arg for a worker.
I did not test with lxc native tools but I hope everything is still OK.
There are some difference between the container build with libvirt:
- It has intentionally no network (except lo), while before all net was available.
- Memory is limited (default to 512MB)
- vm_kill_lxc uses "virsh destroy" while with lxc tools, it uses lxc-stop (which one is right?)
- The libvirt version on sles12sp1 …
> Add support for LXC as libvirt driver

- build-vm-kvm
This is needed so that it works with an armv7 guest.
> build-vm-kvm: use virtio-rng-device also on aarch64

- build-recipe-kiwi
This PR is done to make sure profiled kiwi builds can be done also for the lasted kiwi version (kiwi v8). The profile name should be added in the ID also for kiwi v8 commands, otherwise building multiple profile ends up in multiple images that are named the same, resulting in a failure due to files overlap.
> Profiled bundle

- build-vm-lxc
virsh does not return the error code (other than its own errors)
nor build can retrieve it from swap. So, every failed build was
passed as success.
Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>
> Retrieve exitcode from _exitcode for LXC/libvirt

- build
Build creates root owned files, so this option allows build to be used to also delete those files.
With this, normal users can delete their build-roots while only having sudo rights to the build script.
> Add option to wipe a buildroot

- Build.pm
- createdirdeps
- expanddeps
When there are multiple candidate packages as a result of
Provides, the current obs-build gives an error: "have choice for".
However, according to http://www.rpm.org/wiki/PackagerDocs/Dependencies ,
Recommends tells the system to install the corresponding package
unless there is a conflict; thus, if there is a package recommended
(as described in issue #302), obs-build shall install the recommended
package, resolving "have choice for" error.
Fixes #302
Signed-off-by: MyungJoo Ham myungjoo.ham@samsung.com
> Recognize Recommends relations of RPMs.

- vc
There is no need two end a file with two LF characters — one is enough.
> vc: avoid trailing empty line

- build
switch --wipe cannot work because of typo in function name
wipe_build_environement -> wipe_build_environment
> fixed typo in function name

- build-recipe-kiwi
without this, the kiwi_profile in the calling function will
be modified, resulting in skipped builds for multiple <type/>
definitions in one build, only the first one will be built
I found this out by adding debug into the script, with the following result:
[   85s] debug:build_kiwi_appliance imgtype tbz kiwi_profile '__not__set'
[   85s] debug:build_kiwi_appliance prof '__not__set'
[  281s] debug:build_kiwi_appliance after perform_image_build
[  284s] debug:build_kiwi_appliance after perform_image_bundle: success
[  284s] debug:build_kiwi_appliance after perform_image_bundle: ???
[  284s] debug:build_kiwi_appliance after prof loop
[  284s] debug:build_kiwi_appliance imgtype docker kiwi_profile ''
[  284s] debug:build_kiwi_appliance after prof loop
imagetype is "tbz docker"
As you can …
> build-recipe-kiwi: make kiwi_profile local

- init_buildsystem
this was a copy paste error
introduced in 49eb995467bcbb03b74cd15adf919691c8ab582b
now it is similar to usage in lines 153 164 481
> fix haskell builds (bsc#1018895)

- lxc.conf
tested successfully on Tumbleweed, 42.1, 42.2 and SLES-12-SP2
with lxc versions from 1.1.2 to 2.0.4
lxc is looking for a default apparmor profile, but none are installed in the build environment,
so we tell it to not use any.
> fix build with vm-type lxc

- build-vm-kvm
to KVM
e.g. VM_CUSTOMOPT="-rtc base=2018-02-03T11:22:33"
to allow building with adjusted clock to test future results
for reproducible builds
> allow to pass custom options

- build-vm
to do two parallel builds on one physical host
with two different hostnames
e.g. for verifying reproducible builds
> allow to override hostname

- build-vm-kvm
Appending custom options to the end allows user to override existing qemu options.
For instance, I need to specify -cpu host,-tsc-deadline to prevent guest kernel from crashing.
As soon as -cpu host is already specified, my option has to be after it.
For options not present in default qemu arguments, order is not important.
> Append VM_CUSTOMOPT to the end of argument list

- build-recipe-debootstrap
Debootstrap logs into the the debootstrapped root, so pull the log from
there rather then the build root.
> Correct debootstrap log path

- build-pkg-deb
As the worker roots are transient there is little point in syncing
everything to the filesystem, force dpkg to use unsafe-io.
unsafe-io has been present in dpkg 1.15.8.6, which is older then the
dpkg on any still supported debian or ubuntu release, so should be safe
to do unconditionally
> deb: Force unsafe io when install packages

- build-recipe-livebuild
When ran on Debian testing/unstable, lsb_release --codename will
return "n/a", which results in a broken config.
As a workaround, if "n/a" is returned, parse /etc/debian_version
which will contain "\<testing codename\>/sid".
> livebuild: parse /etc/debian_version on testing

- build-recipe-debootstrap
Based on testing a large set of package it seems the debootstrap build root wasn't completely setup, this resolves some issues that were seen.
> Debootstrap setup

- configs/debian.conf
The Debian/Ubuntu kernel source package builds some userland tools
(perf, etc), so it needs linux-libc-dev. But since it is built from
the same source package, the dependency resolver blacklists it,
making it impossible to build Debian/Ubuntu kernel packages.
Add Keep: linux-libc-dev to the default config to avoid the
blacklisting.
Fixes: https://github.com/openSUSE/obs-build/issues/300
> configs/debian: add linux-libc-dev to Keep list

- build-recipe-debootstrap
At least the systemd testsuite assumes the build environment has /sys
mounted, so lets mount it.
> debootstrap: Also mount sysfs

- build-recipe-debootstrap
To speed up dpkg a little bit one can turn on usage of unsafe-io to
lower the amount of sync() like calls it does. Enable this early in the
debootstrap run.
> debootstrap: Enable dpkg unsafe io usage

- runservices
In my case the buildroot has a double //, but the tempdir generated by $tempdir = File::Temp::tempdir('CLEANUP' => 1, 'DIR' => "$buildroot/tmp");
does not repeat the double //. This causes the subsequent 
die("bad tempdir\n") unless $tempdir =~ s/^\Q$buildroot\E//;
We better reduce and double // in the $buildroot to single / to be safe.
> avoid failing with 'bad tempdir'

- dist/debian.control
- dist/debian.links
- dist/debian.rules
Debian ships build in a package named obs-build. Given the package names are different, but ship the same files, there is a conflict on the file system. This was sent via https://build.opensuse.org/request/show/450943 but it got lost when the files moved into git.
Also add symlinks so that build can work with Debian's version of osc out of the box.
> Debian: fix conflict with Debian's osc and obs-build

- build-recipe-debootstrap
Some packages seemingly rely on apt-cache (with populated caches) being
available during build. This seems an ugly assumption, but it does work on
the Debian buildd infrastructure so make it work on OBS as well.
> debootstrap: generate apt caches

- build-recipe-fissile
otherwise we get errors because "localhost" can't be resolved to "127.0.0.1"
> Instruct fissile to use --network=host when building packages

- dist/build-mkbaselibs-sle.changes
- dist/build-mkbaselibs-sle.spec
That should address the issues reported by repo-checker:
```
found conflict of build-mkbaselibs-20170804-1.1.noarch with build-mkbaselibs-sle-20170804-1.1.noarch:
- /usr/lib/build/baselibs_global-deb.conf
- /usr/lib/build/baselibs_global.conf
- /usr/lib/build/mkbaselibs
found conflict of build-mkbaselibs-20170804-1.1.noarch with build-mkbaselibs-sle-20170804-1.1.noarch:
- /usr/lib/build/baselibs_global-deb.conf
- /usr/lib/build/baselibs_global.conf
- /usr/lib/build/mkbaselibs
```
> build-mkbaselibs-sle: conflict with other providers of mkbaselibs

- vc
when using vc in just_edit mode a newline is added at the beginning of the file.
> vc: prevent leading newline when using the just_edit mode

- Build/Deb.pm
Build-Depends-Arch and Build-Conflicts-Arch where added in dpkg 1.16.4.
They are now documented in man deb-src-control(5) and debian policy.
Add support to obs-build as packages in unstable are starting to use
them.
> Deb.pm: support Build-Depends-Arch

- Build/Deb.pm
Fixes issue #395. Testcase .deb:s at: http://people.linaro.org/~riku.voipio/fix-obsbuild/
Before my patches:
```
528a3601f6d4707259c046c64ec637eb
$VAR1 = {
'provides' => [],
'source' => 'hello',
'hdrmd5' => '528a3601f6d4707259c046c64ec637eb',
'name' => 'hello',
'requires' => [
'libc6 (>= 2.14)'
]
};
hxz.deb: control.tar.gz is not second ar entry
hxz.deb: control.tar.gz is not second ar entry
$VAR1 = undef;
```
And with patches:
```
528a3601f6d4707259c046c64ec637eb
$VAR1 = {
'source' => 'hello',
'requires' => [
'libc6 (>= 2.14)'
],
'provides' => [],
'name' => 'hello',
'hdrmd5' => '528a3601f6d4707259c046c64ec637eb'
};
56be34240ac273298ec9e37bd61b26f2
$VAR1 = {
'source' => 'hello',
'hdrmd5' => '56be34240ac273298ec9e37bd61b26f2',
'name' => 'hello',
'requires' => [
'libc6 (>= 2.14)'
], …
```
> Add support for .deb files which have control.tar.xz 

- build-pkg-deb
Like in Deb.pm, handle the case of control.tar.xz
> build-pkg-deb: support control.tar.xz

- configs/arch.conf
`libpsl` (dependency of `curl`) requires `libidn2` & `libunistring`.
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/libpsl&id=ab7b5d9e584beb55e93a1256db0ee306edd8a6b2
> add libidn2 and libunistring to preinstall for archlinux

- download
This PR switches the download script to use the non-deprecated default implementation (IO::Socket::Ssl) backend for LWP::Protocol::https, enables hostname verification and HTTPS proxying support.
Besides mitigating MITM attacks (without hostname verification, any certificate trusted by the system anchor will be accepted as valid, even though issued for a completely different hostname), this also fixes huge performance problems for HTTPS-scheme downloads.
On my test system, downloading a rather small file over HTTPS took anywhere from 13 to 60 seconds(!) with the deprecated Crypt::SSLeay backend, while the IO::Socket::Ssl backend clocks in at a more reasonable 0.5 seconds on average. This made HTTPS downloads completely unusable.
> Modernize download script.

- init_buildsystem
when building in KVM, we need the preinstalled packages (e.g. rpm)
to install packages, because once we uninstall them, we cannot get them back.
Closes #377
> Keep preinstalled packages

- build-recipe-livebuild
.binary config seems reasonable to allow user to add, as it effect the
final live system.
.chroot is for the livebuild chroot, where there is no network access,
during build on OBS so blocking them seems reasonable.
> Only block .chroot archive config

- changelog2spec
without this,. "foo.changes" will be preferred over
"_service:obs_scm:foo.changes" which means --generatechanges in obs_scm
has no effect.
Debug code put in there (Data::Dumper \@changes and %changes):
old:
```
$VAR1 = [
'_service:obs_scm:foo.changes',
'foo.changes',
'foo-bar.changes'
];
$VAR1 = {
'foo.changes' => 'foo.changes',
'foo-bar.changes' => 'foo-bar.changes'
};
```
(it is actually random, depending on the order, readdir() returns the entries)
new:
```
$VAR1 = [
'foo.changes',
'foo-bar.changes',
'_service:obs_scm:foo.changes'
];
$VAR1 = {
'foo.changes' => '_service:obs_scm:foo.changes',
'foo-bar.changes' => 'foo-bar.changes'
};
```
I guess the _service handling code was inserted at the wrong place accidentally in commit e67b39088c887573c79997b41b22ffab680d8f38
> changelog2spec: prefer _service:.*:.*.changes

- build-vm-docker
syntax error in line 52 of build-vm-docker
> [build] fixed typo in build-vm-docker

- build-vm
According to find's manpage "-perm +mode" is deprecated since 2005.
> Use "-perm /4000" instead of "-perm +4000" in find call

- build-recipe-appimage
Check for the presence of rpm in the build root instead of the
host system. Execute createrepo in the build root and not in
the host system.
Fixes: https://github.com/openSUSE/osc/issues/365 ("cannot build
sample AppImage with osc on ubuntu 16.04")
> Fix rpm detection and createrepo code in build-recipe-appimage

- changelog2spec
- t/changelog2spec.t
for https://bugzilla.opensuse.org/show_bug.cgi?id=1077145
first this introduces a new map_changes function to add selftests
and then fixes a random bug introduced by 393c4906
to always pass the tests.
1st and 3rd commit could be squashed if you want.
> add changes2spec Selftest + fix boo#1077145

- Makefile
e.g. perl-5.26 on Tumbleweed does not have '.' in the default `@INC` anymore
> fix tests on newer perl

- build-recipe-appimage
Otherwise build errors occur when AppImage's auto-detection for the architecture fails, eg.:
```
[  367s] Use appimagetool
[  367s] /usr/src/packages/OTHER /usr/src/packages/SOURCES
[  367s] appimagetool, continuous build (commit 88400e4975cd3fb1270e5a6352a7180195dfae83), build (null) built on 
[  367s] Unable to guess the architecture of the AppDir source directory "/usr/src/packages/Tag Editor-0-Build5.1-x86_64"
[  367s] A valid architecture with the ARCH environmental variable should be provided
[  367s] e.g. ARCH=x86_64 appimagetool ...
[  367s] 
[  367s] cloud136 failed "build appimage.yml" at Sat Feb 10 19:42:41 UTC 2018.
```
I tested locally that passing the architecture manually like this PR proposes works, at least for `x86_64`.
Note that the error message is emitted here: …
> Don't rely on AppImage's auto-detection for architecture

- build-recipe-livebuild
As requested in https://github.com/openSUSE/open-build-service/pull/4526 by @adrianschroeter add sha256sums for Debian image builds, like for the kiwi images.
Also count ONIE images as results.
> livebuild (debian image): produce sha256sum of built images

- expanddeps
- Build::get_sysbuild returns and array where at the first position
is the result of the whole operation. This was not handled properly
for kiwi outputs
> Fix sysdeps parsing in case of kiwi image

- Build/Rpm.pm
This change fixes `getnevr_rich()` function to work correctly with dependencies containing parentheses.
For example, this function was mistakingly returning `rubygem(xpath` when parsing the following rich dependency:
`(rubygem(xpath) >= 2.0 with rubygem(xpath) < 3)`
> Fix rich dependency calculation when dependency name has parentheses

- build-vm-docker
Completely _untested_ (based on the information in
https://docs.docker.com/engine/admin/volumes/volumes/#differences-between--v-and---mount-behavior)
This is needed to support colons in the volume name.
Fixes: https://github.com/openSUSE/osc/issues/358 ("--vm-type=docker
not compatible with build_root with common prj names containing ':'")
> Use docker --mount instead of --volume

- computeblocklists
FIBMAP is deprecated and unsupported on newer file systems, including btrfs.  This pull request adds support for FIEMAP, which maps extents instead of individual blocks.
It resolves https://bugzilla.suse.com/show_bug.cgi?id=1093171
> Iterate over block lists using FIEMAP

- build-pkg-arch
Instead, pass --overwrite '*' to pacman -U, which has the same effect
as the deprecated --force option. Note: this changes assumes that
the pacman -U command supports the --overwrite option (which is ok,
because Arch is a rolling distro).
If you think we should care about backward compatibility with old pacman
versions, I'll happily update the PR:)
> Do not pass the deprecated "--force" option to pacman -U

- spec2changelog
- vc
This PR adds support for "Name <email>" format for author ID in changelog entries. This structure is common among virtually all package changelog formats now (both RPM %changelog and Debian changelog files use this structure).
> Add support for full author identities in changes files

- build-pkg-deb
rcS is a configuration file created by initscripts, not entirely clear
why obs-build tries to create it. But if it does initscripts will ask
whether to keep/replace it interactively blocking the build.
> deb: Don't create an empty rcS

- build-recipe-livebuild
Packages are published with their source tarballs so that they can be
reproduced by users, among other reasons.
Publish the livebuild tarball for those same reasons together with the
ISO files.
> build-recipe-livebuild: publish source tarball

- build-recipe-debootstrap
Without this, calling `su` can fail during PAM authentication. The `su`
from shadow will ignore this error when called by root, but the `su`
from util-linux does not and the build fails.
The outer buildroot configured the abuild user correctly, but the copied
configuration for the inner debootstrap root did not.
> debootstrap: Add abuild shadow password entry

- build
On Ubuntu 18.04, debug packages are called e.g.
php7-mapi-dbgsym_8.6.81.24-0+3.1_amd64.ddeb
> build: collect *.ddeb, *.udeb files too

- build-recipe-debootstrap
debootstrap won't necesserily create /etc/hosts, so copy it from the
main buildroot if it's not there.
Signed-off-by: Héctor Orón Martínez <zumbi@debian.org>
Signed-off-by: Andrew Lee (李健秋) <ajqlee@debian.org>
> debootstrap: ensure /etc/hosts exists

- vc
Otherwise we end up with a broken changes entry if
$mailaddr and $VC_REALNAME are set and $VC_MAILADDR is unset.
> Fall back to $mailaddr if $VC_MAILADDR is unset/null

- configs/arch.conf
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/libarchive&id=82ec2e0ca20e3e3cf29f1bfb2b95dde88da68394
Currently all builds for archlinux are failing with this error:
```
pacman: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory
[   20s] exit ...
```
> archlinux: add zstd to Preinstall for libarchive

- build-recipe-spec
separate our additions from macros that originate from prjconf
> Write nicer .rpmmacros

- build-recipe
Currently, the _statistics file is saved in $TOPDIR/OTHER instead
of $BUILD_ROOT/$TOPDIR/OTHER.
Fixes: https://github.com/openSUSE/osc/issues/449 ("osc build
creates _statistics outside chroot")
> Save the _statistics file in the $BUILD_ROOT dir

- configs/sl15.1.conf
- dist/build.changes
Currently we patched build package in Leap 15.1 https://build.opensuse.org/package/rdiff/openSUSE:Leap:15.1/build?linkrev=base&rev=53 , we need sl15.1.conf being upstreamed and update the content.
> Add sl15.1.conf for Leap 15.1

- baselibs_configs/baselibs_global-sle15.conf
- baselibs_configs/baselibs_global.conf
Since SLE15 the debuginfo files are suffixed with version-release-arch so
the current pattern no longer matches debuginfo files in the glibc
package.  Also, debuginfo files only reside in /usr/lib/debug.
> Fix pattern for debuginfo packages in baselibs_global.conf

- Makefile
- buildvc.1
The command is /usr/bin/buildvc, so the manpage should match that
name.
> Rename vc.1 manpage to buildvc.1

- build-recipe-livebuild
With bash 5.0 echo -e ${build_results} returns nothing even though it is
set:
```
[  368s] + local build_results=
[  368s] + for i in $BUILD_ROOT/$TOPDIR/$LIVEBUILD_ROOT/*
[  368s] + test -f ///usr/src/packages/LIVEBUILD_ROOT/vyatta-master-amd64-vrouter/auto
[  368s] + continue
[  368s] + for i in $BUILD_ROOT/$TOPDIR/$LIVEBUILD_ROOT/*
[  368s] + test -f ///usr/src/packages/LIVEBUILD_ROOT/vyatta-master-amd64-vrouter/binary
[  368s] + continue
[  368s] + for i in $BUILD_ROOT/$TOPDIR/$LIVEBUILD_ROOT/*
[  368s] + test -f ///usr/src/packages/LIVEBUILD_ROOT/vyatta-master-amd64-vrouter/build.log
[  368s] + case "${i##*/}" in
[  368s] + for i in $BUILD_ROOT/$TOPDIR/$LIVEBUILD_ROOT/*
[  368s] + test -f ///usr/src/packages/LIVEBUILD_ROOT/vyatta-master-amd64-vrouter/cache
[  368s] + continue
[ …
```
> livebuild: quote variable to fix error with bash 5.0

- build-pkg-deb
Per invoke-rc.d(8), a local policy script can be created at
/usr/sbin/policy-rc.d to influence how services are started. When this
script exits with code 101, the requested service is not started. This
is independent of init system and is respected by all maintainer
scripts that comply with debian policy.
This is how debootstrap prevents services from running in the chroot. On
more recent debian and ubuntu releases where systemd is in use, it will
prevent services from starting by detecting that it's in a chroot, but
this method works independently of the init system. In our case this
fixes builds on Ubuntu Trusty where upstart is init. This change likely
makes the hack to replace /sbin/start with a symlink to /sbin/true
unnecessary. That hack is not comprehensive since it only handles …
> deb: Install policy-rc.d to prevent services from starting

- build-recipe-arch
GPG signing is not currently supported (https://github.com/openSUSE/obs-build/issues/321)
We want to disable the check so PKGBUILDs relying on `validpgpkeys` can still be built.
> [ArchLinux] Skip unsupported GPG check

- build-recipe-arch
This is only needed in the "prepare" stage.
> [ArchLinux] Only use --skippgpcheck in prepare()

- build-recipe-spec
Without this patch if using the new version (18.12.0) is used all output is
suppressed. This is very confusing as you normally can see the output of
the build process.
This patch enables verbosity level 2, so also the output of the building
process is printed.
This patch shouldn`t harm older versions of debbuild as it had already an
options "-vv". SEE
https://github.com/ascherer/debbuild/blob/18.8.1/debbuild#L304
> add "-vv" parameter in case of debbuild

- configs/sl15.5.conf
Support: brp-extract-appdata was disabled on Factory, remove brp-extract-appdata from config to preventing nothing provides brp-extract-appdata when build rebuilding.
> configs/15.5.conf: remove brp-extract-appdata from support package

- debtransform
Drop build time from Debian .diff.gz
to make package builds reproducible
See https://reproducible-builds.org/ for why this is good.
> Drop build time from Debian .diff.gz

- build
This is needed for the testsuite of util-linux, for example.
> Mount /sys in chroot build

- build-recipe-dsc
The purpose of the changes file is to list everything that is to be
installed into the Debian (or derivative) archive, including *.deb,
*.udeb (micro-debs for the Debian installer), *.ddeb (detached debug
symbols, in Ubuntu and its derivatives) and *.buildinfo (details of the
build environment, mainly for reproducible builds). If we're providing
an equivalent of the Debian archive, then we should include all the
same files.
This change ensures that all build products get moved into the right
place, even if they are file types that obs-build doesn't yet know about,
or even file types that haven't been invented yet.
When obs-build is used in conjunction with OBS, changes to bs_publish
are also likely to be necessary for a full-stack solution.
Signed-off-by: Simon McVittie …
> build-recipe-dsc: Move all build results, not just *.deb and *.changes

- build
- build-vm
- build-vm-nspawn
This change adds support for building inside a lightweight containers created by `systemd-nspawn`.
As Fedora 31 switched to cgroup v2, `lxc` can't support limiting device access to host system anymore.
There are no files in cgroup v2 hierarchy that provide interface to rules for device access: eBPF program should be used instead.
Also, Docker does not work as well with cgroup v2.
This leaves us without working backends supporting lightweight containers, so a new backend that can work with cgroup v2 becomes necessary.
> Add systemd-nspawn backend

- build
gcc-7 is not detected by the regex as it lacks a 2 part version
number and is older than gcc-4.x. Fix this issue by relaxing the
regex when it matches version number.
> fix ccache setup of non-dotted compiler versions

- build
The chroot needs to be done before the recipe code.
Otherwise one can not enter a buildroot from outside
a working directory.
In addition a recipe is not needed to chroot into
an existing buildroot.
Is needed in addition to https://github.com/openSUSE/osc/pull/710
> allow to enter an existing buildroot w/o recipe

- configs/sl15.2.conf
- configs/sle15.2.conf
Since latest rpm in SP2 has BuildRequires libgcrypt-devel to use libgcrypt as crypto library, build config need to adjusted to add preinstall for crypto library.
build fail link: https://build.opensuse.org/package/live_build_log/openSUSE:Leap:15.2:Staging:A/build/standard/x86_64
rpm update: https://build.opensuse.org/request/show/760171
> configs: fix testbuild fail with latest rpm in SP2 and Leap 15.2

- build-vm
the patch add functionality to use a folder (BUILD_ROOT) as base image(VM_ROOT) for kvm based builds by creating the image after BUILD_ROOT is populated there is no `mount` call required. This is necessary for kvm based build in containerized environments with access to `/dev/kvm`. 
The patch checks the `virt-make-fs` binary is available and vmdisk-filesystem is ext3 (restricted as of now).  THe patch also splits `vm_setup()` function into two parts (setup_swap, and setup root) to highlight the difference between the two setups. Swap setup is kept as was. While root (VM_ROOT) setup is conditioned to (presence of virt-make-fs binary and ext3 filesystem).  So the feature can be completely disabled if the binary is not available.
> use virt-make-fs when using ext3 base file system

- build-vm-kvm
as fallback regardless of the platform to have a global fallback
kernel to use for distros that do not use the "kernel-obs-build"
package to provide the guests kernel and initrd as the system
binaries are not reliable for use in a guest system
> build-vm-kvm: use /boot/kernel.obs.build and /boot/initrd.obs.build

- build-recipe-collax
- build-recipe-dsc
- build-recipe-spec
Remove the RUN_SHELL handling in build-recipe-collax,  build-recipe-dsc and  build-recipe-spec. With the new logic introduced by @adrianschroeter these codepaths are not reached anymore.
> remove old shell behavior in recipe scripts

- build
- build-recipe
It should fail on purpose, when no script is available, but the feature
is configured
Not using kiwi_post_run to allow this feature independend of the build
tool
> call obsgendiff if configured

- build
A full filesystem which is hosting the root fs file is considered
to be a badhost setup.
Just never run inside of the VM
> running disk full check also outside of VM

- build-vm-nspawn
This change fixes an oversight that was made when implementing `systemd-nspawn` driver.
It's not enough to return error code from `vm_startup_nspawn` function, `cleanup_and_exit` should be called with exit code as argument.
> Return correct exit code from systemd-nspawn build

- build
and free disk space by removing the archive
> handle obscpio extraction error as fatal

- build
- build-vm
with `--ccache` every build will generate a `OTHER/_ccache.tar.gz` archive
which can be used for subsequent builds. However for local builds
explicit path to archive with `--pkg-ccahe` is necessary.
A user provided archive can be used as ccache contents with
`--pkg-ccache=/path/to/archive.tar.gz`
`--pkg-ccache` will override the default ccache. (`--pkg-ccahe` implies
`--ccache` but with provided archive)
> extend --ccache to generate _ccache.tar.gz and implement --pkg-ccache

- build-recipe-kiwi
This commit adds support for Arch Linux repositories in the KIWI
build recipe.
> Add support for Arch in build-recipe-kiwi

- build-vm-nspawn
The `--pipe` option of `systemd-nspawn` is useful for automated build, but it leads to very inconvenient results when running interactive shell using `osc shell` command: pressing `Ctrl+C` causes the whole session to terminate.
Also, `--pipe` option is not available on older versions of `systemd-nspawn`, like the one that is used in Raspbian 10.
This change makes `build-vm-nspawn` autodetect whether `--pipe` option is available, and use it only for automated build, but not interactive shell.
> Autodetect whether to use --pipe option of systemd-nspawn

- build-vm
It used to be enabled by initrd before, but we need
to do this on our own meanwhile.
> enable sysrq operations on boot

- build-vm-zvm
- Use ZVM_VOLUME_ROOT and ZVM_VOLUME_SWAP variables to define the local
zVM environment
- Increase wait to connect iucv console to 5 seconds. This is not
critical, since the messages are buffered, however I encountered
connection fails with 2 seconds.
- Add new function vm_initrd_obs_modules_zvm to create new worker initrd
on demand. This uses the initrd created by the obsworker script and
updates the kernel modules within according to the OBS kernel.
The resulting initrd is stored at the same location as the obsworker
initrd, however expanded with the actual kernel version and thus
cached for subsequent builds.
> Update for zVM to make container builds work.

- build
this folder wont be present when calling
osc build --pkg-ccache /path/to/_ccache.tar
> create folders before trying to copy ccache.tar

- build
use evict-older-than from ccache if available to remove files older
than those used for current build.
> cleaning ccache

- build-vm-zvm
in z/VM, the virtual hardware can either just continue running or power off after shutdown of a linux VM. If it is powered off, the disks are already detached, thus nothing to do anymore.
> Ignore, if shutdown behavior changed by build in z/VM

- build-vm
"spectre_v2=off" is x86-specific and would require "nospectre_v2" instead to be
architecture-independent. But there is also a shorter option called
mitigations= that includes nopti, kpti, etc.
> Use shorter kernel flag for mitigations

- baselibs_configs/baselibs_global-sle12.conf
- baselibs_configs/baselibs_global-sle15.conf
- baselibs_configs/baselibs_global.conf
pkg-config files are interesting for development, so include them here.
e.g. used by wine development of 32bit
> also package pkg-config files by default into baselibs. (bsc#1172563)

- dist/build.spec
With Fedora 33 the POSIX perl module was split out of the perl package.
This patch addeds Requires and BuildRequires for the perl POSIX module.
> fix dependencies for Fedora 33

- build
Setting cache_dir in the config file directly make sure ccache obeys it.
If for some reason the ENV variable is not loaded then ccache default to
/home/current_user/.ccache, which breaks the entire implementation.
some reformatting for better readability. ( and white space changes)
> set cache_dir directly in ccache config and cleanup corres. code

- build-recipe-docker
- obs-docker-support
A Dockerfile may have "USER root" in the beginning to switch
back to root user, because the base image has defined a non-root
user via USER statement.
We must install obs-docker-support therefore before the first
RUN instead of after FROM line to be root at that point of time.
>     Support root switching in Dockerfile

- build-recipe-spec
checking for /usr/bin/rpmlint as fallback for OBS-70
> support rpmlint on non-SUSE systems

- init_buildsystem
The to be downloaded packages are stored in
"$BUILD_ROOT/.init_b_cache/rpmlist.download" instead of
"$RPMLIST.download". Also, get rid of the useless use of cat.
> Fix download progress in init_buildsystem

- init_buildsystem
Depending on worker and its storage performance, this can shave tens of seconds off a package build that likely has no use for system manpages anyway.
> init_buildsystem : skip "Processing triggers for man-db..." when building DSC

- Build/Docker.pm
- Makefile
- build-recipe-docker
- patchdockerfile
also fixes issue if no RUN line is inside of Dockerfile (section)
Additional perl helper is used now instead of simple sed replacement.
We must enable obs-docker-support after a possible existing "USER root"
line or after each FROM line.
disable must happen before a USER line (except it is the "USER root"
line) or at the end of each section
> Support Dockerfile builds with multiple FROM sections

- Build.pm
Upstream added `%arm64` in https://github.com/rpm-software-management/rpm/commit/b533164b25052adb78faf6ec57742f280940a172
> Add %arm64 from upstream to std_macros

- build-recipe
We will drop the single obsgendiff hook, since it is relative new to
avoid confusion later.
> execute all obsgendiff.d scripts

- build
This further reduces disk space consumption
> remove ccachetar after it has been extracted.

- Build/Helm.pm
already deployed to fix failures during builtime source service runs
> avoid hard requirement to Digest:SHA for all modules

- configs/sl15.5.conf
- download
Without this patch SUSE-connect credentials are not used when downloading
packages from zypp:// urls in a local build.
This patch changes the download mechanism for zypp:// urls from LWP::UserAgent
to system call of "zypper download"
Fixes: #boo1148916, #1174042
> use "zypper download" for zypp:// urls

- build
- build-vm
Fatal errors say that another attempt to build on this host should be
avoided. This is the case when the storage can not be created or
formated.
> report fatal error in case of fundamental build root setup

- build-recipe
It used to be single script only.
The new way is to place scripts into
/usr/lib/build/obsgendiff.d/
directory
> cleanup old obsgendiff execution way

- Build.pm
- Build/Flatpak.pm
If the parsing fails, the script needs to die.
> Flatpak: Handle errors in show function

- build-recipe-debootstrap
When attempting to build Debian unstable, distribution is
calculated using lsb, which relies on apt cache.
As our build systems lack apt cache and network we cannot detect
we are building for Debian SID (aka unstable).
For more background information see:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=845651
Tested-by: Héctor Orón Martínez <hector.oron@collabora.co.uk>
Signed-off-by: Andrew Lee (李健秋) <ajqlee@debian.org>
> build-recipe-debootstrap: add fallback for Debian SID distro

- build
- build-vm
This will reduce the build speed but make the ordering of entires in
the filesystem reproducible.
It can be enable via CLI switch or via config option. eg
BuildFlags: vmfstype:ext4:nodirindex
> introduce the option to disable dir_index in ext fs

- build-vm
This keeps the vmfstype option compatible with old build scripts
new way is
BuildFlags: vmfsoptions:nodirindex
> use addition buildflag for nodirindex option

- build
this suffix is mandatory and should either be s(econds)/d(ays).
this patch tries both (with and without suffix), avoiding to do any
complex checks for version (ccache -Version). The version comparison
would need either need floating point comparision or extracting major
and minor version and comparing those.
The with_suffix variant is tried first as it is what will be supported
going ahead.
Would be nice to have a second pair of eyes for the bash !
> ccache: it was updated to expect a suffix for -evict-older-than option

- Build/Flatpak.pm
- build-recipe-flatpak
- call-flatpak-builder
- t/data/flatpak.json
- t/data/flatpak.yaml
- t/flatpak.t
The downloadable files need to have versions, but flatpak
manifests don't have version fields.
> flatpak: Allow to specify #!BuildVersion

- dist/build.spec
We're not using it anywhere, and we shouldn't, since it's outdated and
broken.
> spec: Remove YAML.pm requirement

- Build/Flatpak.pm
- build-recipe-flatpak
- t/data/flatpak-rewritten.yaml
- t/data/flatpak.json
- t/data/flatpak.yaml
- t/flatpak.t
This allows users to keep the original url in the flatpak manifest
for reference.
At build time flatpak-builder will work with the file urls.
> flatpak: Replace source urls with file paths

- build-vm
if the scheduler tried to abort our jobs while we
are in the preparation phase (before vm is launched)
try to exit more gracefully
silence error message from objdump examining kernel file type
> build-vm: check_exit again after copying old packages

- build-vm
otherwise all workers try to lock /var/tmp/.guestfs-0/lock (and deadlock) and we do not just want to cluttter / of the worker machine anyway
> build-vm set LIBGUESTFS_CACHEDIR to prevent deadlocks

- pbuild
it appears without reversing the configs the oldest entry in the
project config path actually win.
> pbuild: reverse collected projectconfigs

- build-recipe-docker
Pass --cgroup-manager=cgroupfs to podman as the default is "systemd" which is
not available in the build env.
Tested with a local `osc build` after patching `/usr/lib/build/build-recipe-docker`.
> build-recipe-docker: Fix builds with podman

- build
vm_detect_2nd_stage can call cleanup_and_exit before setting
RUNNING_IN_VM=true. Thus, buildroot_umount, which is defined in the
common_functions file, can be called by cleanup_and_exit. Hence,
source the common_functions file before calling vm_detect_2nd_stage.
Note: if sourcing the common_functions file fails, we still call
cleanup_and_exit and the umount fails. However, all other cleanup
actions are executed.
> source common_functions early

- .travis.yml
- build-recipe-flatpak
- t/data/flatpak.sh
- t/data/mahjongg/flatpak.yaml
Also remove the explicit modprobe call, as this shouldn't be necessary.
This test builds the Mahjongg app, and if successful, it installs
it via flatpak and checks if the version output of the app
is as expected.
travis CI probably needs to be enabled here first. Here is the successful build from my fork:
https://travis-ci.com/github/perlpunk/obs-build/builds/219863126
edit: Oh, Travis CI is already active
> Add a Travis CI test for building a flatpak app

- build
Execute every script inside of /usr/lib/build/post-build-checks/ .
The check must validate that it runs for the right build type and fail
only when it finds a problem with a build result. No matter of which
type.
We already have usr/lib/build/checks/ but the existing checks are rpm
generic and fail on non rpm builds. Ideally these get migrated later on.
OBS-110
> add generic post build check script hook

- dist/build.spec
During Factory staging bootstrap, rpmlint-Factory is not available
> Fix bootstrap build

- build
Sccache is an alternate build caching system to ccache/icecream. It
supports C, C++ and Rust. It can optionally have distributed or remote
caches via redis, s3 object stores, memcached, azure storage or
google cloud storage.
This can help to significantly improve the performance of Rust rebuilds.
For example, Kanidm changes from 400s to 122s on a rebuild, and rust-lang
rebuilds improve from 7200s to 4770s. With some changes to the rust
packages especially this will be possible to speed up over version
changes as well.
> Add support for sccache.

- build-recipe-docker
- call-podman
on a tumbleweed host, podman defaults to use crun, which is able to deal with the enabled unified cgroupv2. However older versions of podman (like SLE) don't have support. so detect in which situation we are, and hardcode runc if crun is not available inside the buildroot.
> enforce use of runc

- build-recipe-arch
Without this patch `bsdtar` exits with the following error:
```
[   68s] ==> WARNING: Skipping verification of source file PGP signatures.
[   68s]     obs-service-tar_scm-0.10.22.1615538418.07a353d.tar.gz ... Skipped
[   68s] bsdtar: Pathname can't be converted from UTF-8 to current locale.
[   68s] bsdtar: Error exit delayed from previous errors.
```
> set LANG=en_EN.UTF-8 for makepkg in Arch Linux

- PBuild/Job.pm
- PBuild/Options.pm
* Make the shell accessable
* No watchdog running
It still needs --rebuild or --singlejob option.
> pbuild: fix --shell option

- build-vm
This appears to be needed for selinux to work. without selinux
enabled, appliance builds seem to fail
> build-vm: try mounting selinuxfs

- spec_add_patch
Without this patch,
%autosetup caused it to die in line 131
and %autopatch succeeded but would fail to build
because it applied the patch twice.
Might fix https://bugzilla.opensuse.org/show_bug.cgi?id=1172891
I tested this patch on `%setup`, `%autosetup` and `%autopatch` cases.
The -p level is ignored
> Support autosetup and autopatch

- patchdockerfile
Do not run obs-docker-support when building from scratch since it will fail anyway because of missing /bin/sh.
Fixes https://github.com/openSUSE/obs-build/issues/673
> Fix Dockerfile builds FROM scratch

- build
This allows tar's to be used as uris in sccache, where the tar will be extracted to the build root, and subsequently extracted from the root to the original URI for persistence.
> Add ability to use file:/// uri's

- init_buildsystem
/etc/mtab of the build root should be a symlink of /proc/self/mounts,
like on a real root, to reflect the actual mount status instead of the
static (outdated) information of when the build root is started. One
Known failure due to outdated mount inforamtion is when executing the
tests of ostree package, which calls fusermount command, which checks
/etc/mtab. This is also reported in isseu #535.
Signed-off-by: Kai Liu <kai.liu@suse.com>
> init_buildsystem: make /etc/mtab a symlink

- build-recipe-docker
Use $BUILD_ROOT instead of BUILD_ROOT.
Fixes: 121b73960854ba4b041305acaab88caa4442309e ("Rework source
copying code")
> Fix typo in build-recipe-docker

- build-vm-kvm
if kernel cmdline parameters are specified, use those
and only fall back to our parameters if not otherwise specified.
> Rework vm_cmdline handling for kvm case

- build-vm-kvm
- dist/build.spec
Remove an outdated check for qemu 2.5 or older - that should
no longer be an issue.
> Enable tunings also for aarch64 and 32bit x86 builds

- build-vm-kvm
The deprecated compat cpu property has been removed.
> Handle QEMU >= 6.0 on POWER9

- build
- build-vm
the bash builtin $SECONDS allows access to the same
information without having to go through a fork/exec()
path
> Remove subshell usage for determining timing

- build-pkg-deb
- build-recipe-kiwi
- build-vm
- build-vm-zvm
- init_buildsystem
cp(1) has a --remove-destination which does that implicitely,
which avoids calling rm and thereby reducing overhead of
execution
> Avoid calling rm X just before cp A X

- build-pkg-rpm
- dist/build.spec
- dist/debian.control
- init_buildsystem
We can use xargs(1) to batch up invocations, which significantly
improves performance as we reduce the overhead of external
command invocation.
> Avoid calling external commands in a loop

- build-vm
not all older kernels support it, and it really doesn't matter
for build jobs..
> turn off metadata_csm

- build-pkg-rpm
instead of calling rpm --showrc for every preinstall, call it only
once for each compression format. this reduces overhead (always 3 calls
instead of one call per preinstall - typically there are 10+
preinstalls).
> Speed up rpm preinstall

- PBuild/RemoteAssets.pm
- download_assets
to remove all files and directories which are referenced by remote asset urls.
> add download_assets --clean option

- Build/Docker.pm
Fixes issue build#751
with such lines in Dockerfile:
FROM opensuse/leap:15.3 as base
FROM base AS build
> Avoid additional container dependencies when using container alias names

- build-pkg-rpm
the pattern of rm $b; cp $a $b can be transformed
into cp --remove-destination $a $b which saves one
external shell function call
> one more case of rm/cp that can be optimized

- Build/Docker.pm
Always parse them in if _and_ else conditions as we can not judge
about the runtime check
> docker: support package installation calls inside of if conditions

- build
- build-recipe
- build-recipe-kiwi
- build-recipe-spec
buildtime source services may need them
also non rpm builds may need them
code duplication in kiwi part can also be resolved.
> setup rpmmacros for all build types and earlier

- Build/Kiwi.pm
This should be default, but changing the default would break existing
aggregates.
This has also a limitation that it only works properly when build just
one profile per build atm.
> KIWI: Allow to extend cointainer name with profile

- PBuild/Util.pm
- build
- download_assets
We currently use these marker files for remote assets. A more descriptive
file may replace this this later.
> copy source directories also when marked with .build.assets file

- build-vm
But still show all the errors like running out of disk space
and the like.
> avoid printing transfer output

- build-recipe-spec
By undefining %_enable_debug_packages , debuginfo package will not be
created by rpmbuild on Red Hat variant Linux.
Signed-off-by: Kai Liu <kai.liu@suse.com>
> Support OBS Debuginfo build flag for Red Hat variants

- init_buildsystem
SUSE post-build-checks create the abuild user. Need to export the
correct UID and GID for that.
> Export ABUILD_UID to finalize scripts

- PBuild/Cando.pm
- common_functions
armv8 is considered meanwhile fully backward compatible to armv7
in latested tooling (rpm, zypper).
This may not be true for the concrete hardware implementation, but in
general armv8 is a subset of armv7 user land ABI.
> Declare armv8 and armv7 compatible

- build-vm
noxfer still prints how many blocks were copied which is
distracting
> use dd status=none

- build-vm
This avoids a bit of I/O churn and CPU overhead as it also turns
of checksumming.
> use nodatacow for btrfs filesystems

- init_buildsystem
This appears to be older than SLES9, so we don't care
anymore
> remove switch2mesasoft test

- build-recipe-preinstallimage
This looks a bit weird in the build logs
> Run zstd without progress indicator

- pbuild
Download.pm has been moved to Build via 55450de8c4b219bdf63358ee2840cfad55409838
> Fix "Can't locate PBuild/Download.pm"

- build-vm-lxc
LXC 4 introduces no incompatibilities with LXC 3 regarding configuration and command line options that `build-vm-lxc` uses.
Hence, this change just makes `build-vm-lxc` recognise version 4.
> Add support for LXC 4

- build
- build-vm
In most cases a remount -o ro / succeeds wwhich should force flushing
of writes. if it fails we can wait for dirty to be zero.
Typically this reduces the sleep 3 in that code path to 0.1-0.2s.
> Use faster VM shutdown alternative

- build
Testing with Rust + LLVM shows that we can reduce this to 1.2G and
still retain an effective cache for a package. This will reduce
OBS/IBS storage requirements and improve performance of setup/teardown
> Change sccache default size limit

- Build.pm
if not overwritten it expands to empty anyway.
> Export build-packages for all build types

- build-vm-kvm
liburing.so.1 seems to have occassional locking races causing it
to hang on I/O. Accept liburing.so.2+
> only use aio=io_uring if built against new enough liburing

- build-pkg-deb
man-db takes a lot of time when a lot of packages are installed, and it's really pointless for package builds.
dpkg triggers are intended to be ran after a batch of packages have been installed, and that's how `apt` and friends run them, but here `dpkg --install` is ran manually so the triggers run after each individual package install, which is slow. Run dpkg with `--no-triggers` if it's available. The existing `dpkg --configure` call at the end of the installation will run the triggers.
> deb: defer dpkg triggers until all packages are installed, and disable man-db altogether

- build-vm-kvm
The issue has been fixed in SLE15-SP4 Updates
(bsc#1199011, actually security update bsc#1198811 CVE-2022-29582)
This reverts commit 1a81d60cdb93f3486e12ae95e38d6df94fbe05c2.
> Revert "avod aio=io_uring for now on SLE15-SP4 workers"

- .github/workflows/linux.yaml
CI step "Install debdiff for debtransform test" fails with error.
`Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/l/lintian/lintian_2.62.0ubuntu2_all.deb   404  Not Found`
Updating the package indexes before installing the package will fix the error.
> CI: Add package repository update

- build-vm-kvm
Fix indentation in `if` block of `build-vm-kvm` file
> Fix indentation

- build
build uses ulimit -v (RLIMIT_AS) to limit the memory of the build
environment but that limits the size of the virtual address space
rather than how much memory is allocated.  Prior to Linux 4.7,
the RLIMIT_DATA limit which does limit process memory allocation only
covered brk() and sbrk().  "Modern" malloc implementations usually use
anonymous mmap ranges to ask the kernel for memory.  In Linux v4.7,
the RLIMIT_DATA limit was extended to include those.  ulimit -d
controls the RLIMIT_DATA limit, so let's use that instead.
This fixes build failures due to "Out of Memory" when the project
being built does lots of read-only file mmaps, which claims lots
of address space, but uses very little memory.
> build: use ulimit -d instead of ulimit -v (#854)

- build-vm-kvm
This reduces the IPIs on NUMA machines, which should stabilize
performance. See https://git.qemu.org/?p=qemu.git;a=commit;h=14c985cffa6cb177fc01a163d8bcf227c104718c
for details.
> build-vm-kvm: enable l3-cache on i386/x86_64 builds

- build
- build-vm
- build-vm-docker
- build-vm-emulator
- build-vm-kvm
- build-vm-lxc
- build-vm-nspawn
- build-vm-qemu
- build-vm-uml
- build-vm-xen
Works only if `--vm-type` option is specified.
Sometimes it's necessary to add extra options to a VM running on a specific worker. For example, Oracle Linux 8 runs quite old `systemd-nspawn` that knows nothing about faccessat2 system call and filters it out using `seccomp` system call filter, breaking newer `glibc`. A workaround is to pass `--system-call-filter=faccessat2` option to `nspawn` VM on OBS workers running on these systems.
This change implements `--vm-args` option that allows to pass extra arguments to many (but not all) VM types. Other VM types just ignore this option.
Corresponding PR for OBS to utilise this feature is here: openSUSE/open-build-service#12660
> Pass VM-specific extra args to VM using --vm-args option

- configs/sl11.1.conf
- configs/sl11.2.conf
- configs/sl11.3.conf
- configs/sl11.4.conf
- configs/sl12.1.conf
- configs/sl12.2.conf
- configs/sl12.3.conf
- configs/sl13.1.conf
- configs/sl13.2.conf
- configs/sl13.3.conf
- configs/sl15.0.conf
- configs/sl15.1.conf
- configs/sl15.2.conf
- configs/sl15.3.conf
- configs/sl15.4.conf
- configs/sl42.1.conf
- configs/sl42.2.conf
- configs/sl42.3.conf
- configs/sles11sp2.conf
- configs/sles12.conf
- configs/sles15.conf
- configs/sles15sp2.conf
- configs/sles15sp3.conf
- configs/sles15sp4.conf
- configs/tumbleweed.conf
This relates to https://bugzilla.opensuse.org/show_bug.cgi?id=1187749
It resolves failing dependency resolving during build env setup:
This is also reproducible on an openSUSE 15.4 system:
```
Loading repository data...
Reading installed packages...
Resolving package dependencies...
Problem: nothing provides 'rpmlint-mini' needed by the to be installed rpmlint-Factory-1.0-3.19.noarch
Solution 1: do not install rpmlint-Factory-1.0-3.19.noarch
Solution 2: break rpmlint-Factory-1.0-3.19.noarch by ignoring some of its dependencies
Choose from above solutions by number or cancel [1/2/c/d/?] (c): Resolving dependencies...
Resolving package dependencies...
Nothing to do.
```
> configs/*.conf: Stop using rpmlint-mini and rpmlint-Factory.

- lxc.conf
The AppArmor profile name changed from `lxc-default-with-mounting` to
`lxc-container-default-with-mounting`, so reflect that in `lxc.conf`.
Fixes: https://github.com/openSUSE/obs-build/issues/524
Note that this probably breaks older systems, where the AppArmor profile name was still `lxc-default-with-mounting`, but that's likely not relevant to the current development version of `obs-build`.
> [lxc] Update AppArmor profile name

- build-vm-kvm
Reverts openSUSE/obs-build#853
The usefulness of this patch is not clear, host-cache-info should be the default which provides actual information rather than emulated information.
> Revert "build-vm-kvm: enable l3-cache on i386/x86_64 builds"

- build
- build-recipe-docker
- build-recipe-spec
- build-vm-nspawn
grep 3.8 starts throwing warnings, and `egrep`/`fgrep` will be dropped long term
https://bugzilla.opensuse.org/show_bug.cgi?id=1203092
> Convert obsolete egrep/fgrep calls to grep -E/-F, respectively

- build
- build-recipe-livebuild
livebuild stopped working some time ago:
[   48s] -----------------------------------------------------------------
[   48s] ----- building standard.livebuild (user abuild)
[   48s] -----------------------------------------------------------------
[   48s] -----------------------------------------------------------------
[   49s] su: Critical error - immediate abort
[   50s] su: Critical error - immediate abort
https://build.opensuse.org/package/live_build_log/home:bluca:debian_secure_boot/example-images/img_nokernel/x86_64
Run it as root instead of abuild like other image build systems, and use sh -c.
> build-recipe-livebuild: run as root with 'sh -c' instead of 'su -c ... - root'

- build-vm
Some minimal coreutils installations like toybox provide halt, but it does not support the -p option. As halt -p is equivalent to poweroff, we use that instead and can then build toybox successfully
> [build-vm] use poweroff instead of halt -p

- build-vm
- common_functions
- dist/build.spec
- init_buildsystem
The code was setting the executable flag on the host system not inside the build environment where it is needed, hence it didn't work.
> fix initvm executable flag handling

- build-vm
mkfs needs to see the files it copies into the fs as owned by root.
Otherwise the whole fs tree would be owned by the calling user. Doesn't
matter too much when setting up the build root initially as rpm is
called inside anyway to fix everything. However, when reusing an image
suddenly all ownerships would change.
> Fix ownership of VM files of unprivileged builds

- test/libdummy1.spec
"GPL" has never been a valid license string, and it is now a fatal error. use "MIT" from https://spdx.org/licenses/
> fix build of testsuite spec file

- PBuild/Job.pm
`ls` from `PBuild::Util` is not in the global namespace and referencing it without the full namespace results in errors like:
```
Undefined subroutine &PBuild::Job::ls called at /usr/lib/build/PBuild/Job.pm line 348.
```
> Call ls using its full name

- build-vm-kvm
Old build script code was limiting cpu to power8 when building on power9 always.
As this blocks any future development and also is only done on this particular platform this way we change it by default. So KVM on power9 is not special anymore and uses the cpu by default as with any other architecture or VM type.
A buildflag kvm-max-cpu-compat-power8 can be set to restore the old behaviour.
> INCOMPATIBLE CHANGE: get rid of the power8 cpu limitation

- build-vm-kvm
It appears there is a new regression on QEMU 7.1.0 (worked on 7.0) where iothreads together with aio=io_uring hang. As aio=io_uring is slightly faster, we disable iothreads to avoid the hang but still have some performance gain.
> Skip iothreads on QEMU 7.1.0

- build
- build-vm
The default permissions of `ptmx` device in `devpts` filesystem are `000` (none), making virtual terminals not available to regular users.
This causes some packages (like `pytest`) to fail tests that need virtual terminals.
This change adds a mount option specifying permissions of `ptmx` device in `devpts` filesystem, making virtual terminals vailable to regular users.
> Fix permissions of /dev/pts/ptmx to make virtual terminals usable

- vc
Right now the tempfile when invoking the `osc vc` command has a naming scheme that results in something like `package.changes.vctmp.slkqwo`. This has the problem that editors then can't as easily detect that it is a `.changes` file. This PR changes the naming scheme so that it would be something like `vctmp.slkqwo.package.changes`
> Better filetype detection for temp changes files

- baselibs_configs/baselibs_global.conf
We can use the baselibs magic to move the libraries built for x86_64_vX architecture into the hwcaps overlay directory and repackaging them as x86_64.rpm.
> configure mkbaselibs to create glibc-hwcaps baselibs as well

- mkbaselibs
This is needed to avoid the '$_ undefined variable' errors introduced by the last change.
> Merge filelist move logic into a single iteration loop

- vc
This reverts commit df38e6fa5dc1e1bdc102a2f1c183224d0f0fae71.
The change broke creation of .changes files in packages which have an upper X in their name.
```
01:31 a4:../XOrg/libX11 $ osc vc
mktemp: too few X's in template ‘vctmp.XXXXXX.libX11.changes’ /usr/lib/build/vc: Can't create temp file, exiting...
```
Fixes: #905
> Revert & Redo "Better filetype detection for temp changes files"

- obs-docker-support
Without this it is hard to understand for the user why this happened.
> Explain why obs-docker-support failed

- build-pkg-rpm
The conversation of directories to symlinks breaks rpms and that breaks situations where host rpms provides files for the sysroot system.
So we move them away before creating the sysroot and copy them back in afterwards (expect they got also provided by sysroot).
> Fixing/workaround sysroot builds for usrmerge distros.

- build-recipe-docker
- call-podman
This avoids file conflicts when building the same container also for MS-Windows or MacOS
> docker: include OS name in build result if != linux

- startdockerd
If cgroup v1 is used, neither /sys/fs/cgroup/unified nor /sys/fs/cgroup/cpu.stat exist, so it goes into the fallback path to mount the cgroup hierarchy manually. This is mounted on top of the actual cgroup mounts, breaking them. Fix this by recognizing a working cgroupv1 mount.
> Fix startdockerd with cgroup v1

- docs/cross_arch_build.adoc
- docs/pbuild.html
Some of BuildFlags is missing in HTML.
4.6 Build Config chapter is redundant.
4.5 Repository setup seems like missing context so remove it.
> Remove blank paragraphs and regenerate the html

- Build/Rpm.pm
rpm(1) actually parses Patch and Source lines in a special way, it can skip over any non-whitespace until the next ':' as part of the patch suffix determination.
So things like
Source  foo: https://host/domain/file.tar.gz
are possible and need to be parsed properly.
> Parse Patch and Source lines more accurately

- build-vm
Pass-through `--buildtool-opt` into VMs to fix
osc build --vm-type=kvm --build-opt=--buildtool-opt=--noclean
> Pass-through --buildtool-opt

- build-recipe-docker
- docs/build_config.adoc
podman, unlike docker, defaults to oci. Allow setting that as well but default to be docker compatible with allowing the docker extensions.
> Produce docker format containers by default

- Build/Rpm.pm
in spec files with subpackages, %VERSION refers to the main package version while %version refers to the subpackage. Similarly for %url and %URL. The latter is sometimes used in Source lines so we need to be able to expand it.
> Support uppercase macro expansion for tags from the main preamble

- build-recipe-docker
- build-recipe-kiwi
- generate_sbom
Also add the option --tar for container tar balls. But without enforcing it to stay backward compatible.
> generate_sbom: add help option

- build-vm-podman
With the default crun runtime of podman, "osc build" fails because the
--mount option with destination=/ doesn't seem to be supported:
Error: OCI runtime error: crun: mount `/mnt/git/build-root/15.5-x86_64/.mount` to ``: Invalid argument
fcrozat told me on Slack that setting runc as runtime works, and
indeed it does. But if build depends on this, it should rather set
this runtime explitly.
Signed-off-by: Martin Wilck <mwilck@suse.com>
> podman: enforce runtime=runc

- test/libdummy1.spec
RPM went a step further for reproducible builds and extracts the date of the most recent changelog entry. We can provide this by a single dated changelog entry in the rpm directly. Alternative would be adding a .changes file, which seems a bit excessive here.
> test: Add a dated changelog entry to libdummy1.spec

- spec_add_patch
Replace [deprecated usage of `%patch$N`](https://github.com/rpm-software-management/rpm/blob/5b8b8d5a7383c18309e1dd399de875904dbd3ad7/docs/manual/spec.md?plain=1#L529)
with `%patch -P$N`
for compatibility with rpm 4.20
> Replace deprecated %patchN usage

- build-recipe-dsc
In that case modified versions will have been generated as part of the build output. So this avoids coping out two dsc sources, which can cause issues for the source service and schedular trigger dependency rebuilds, or publish hook publishing .dsc source package.
This has happend since the merge of d995de1 dsc_move_build_result() will copy out both original and new one generated .dsc that is list listed in the .changes files. The .changes files list all the modified sources as well as the packages so can be consider definitive.
Closes: 928
> Only copy modified dsc sources listed in .changes if OBS-DCH-RELEASE set

- Build/Mkosi.pm
- PBuild/Container.pm
- PBuild/Job.pm
- PBuild/Recipe.pm
- PBuild/RepoMgr.pm
- build-recipe-mkosi
- build-vm
Not sure how this worked before. Detecting mkosi recipes didn't work and some of the options used are deprecated.
With the commits provided here, mkosi starts to build for me in pbuild but runs into issues later. 
A config file for mkosi has to specify a distribution so mkosi knows eg what package manager to use. Then the distro comes with a set of default packages that are installed always. The build script cannot know about that before setting up the chroot as the list is part of a package of the target system.
cc @bluca
> mkosi fixes

- build-recipe-livebuild
- generate_sbom
Added support for debian images to generate_sbom.
It checks if it is a debian based image by evaluating the os-release file.
It introduces some new BuildFlags to configure "special" behaviour:
`spdx-declared-license:NOASSERTION` licenseDeclared in spdx info for a package is set to "NOASSERATION",
if not set the found license from the package information is used (like for "licenseConcluded").
The license information is taken from the package's copyrightfile.
The generation of spdx' file section can be disabled, if just the package information is wanted.
This can be switched by buildflag "spdx-files-generation". To switch it off it has to be set to "no":
`spdx-files-generation:no`.
Default is to generate also the files information. This option is just available in the deb-handling. No …
> Adding debian support to generate_sbom

- configs/tumbleweed.conf
Change needed to address this new test failure:
https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:A/build/standard/x86_64
gettext-runtime is splitting out envsubst (andenvsubst-mini); the mini flavor does, as usual, require `thisis-only-for-build-envs' which is to be ignored by OBS/build
> config: sync Tumbleweed config

- dist/build.spec
A worker system may have obs-worker installed, but because /usr/bin/build is transferred from obsrepserver, the dependencies of obs-build are not carried over. KVM builds thus fail complaining about absence of mkfs.ext4, mkfs.xfs or the hostname utility (especially if one used zypper in --no-recommends obs-worker, but that's another story).
> dist: add more required recommendations for KVM builds

- build-vm-qemu
This is needed for openjdk which does not support sv57.
> build-vm-qemu: force sv48 satp mode on riscv64

- build-recipe-mkosi
With the .sha256 file generation, `Repotype: checksumsfile` should work.
CC @bluca
> Some mkosi fixes

- Build/Arch.pm
Currently OBS has a problem with file lookups for the Arch repo, resulting in potentially incorrectly generated `.files` files (missing path prefixes).
As described in https://perldoc.perl.org/Archive::Tar::File :
> `$path = $file->full_path`
> Returns the full path from the tar header; this is basically a concatenation of the prefix and name fields.
Using only `name` will result in the loss of the `prefix` part, e.g. `usr/lib` or `usr/lib/python3.xx` in some python packages.
> fix file path for Arch repo

- Build/Arch.pm
Currently Arch build script does not filter out unsupported architectures in `arch=()` and set `exclarch`.
According to [ArchLinux Ports RFC](https://gitlab.archlinux.org/dvzrv/rfcs/-/blob/rfc/arch_linux_ports/rfcs/0032-arch-linux-ports.rst), the `arch` field for PKGBUILDs is now not limited to x86 architectures such as x86_64 i386
> exclude unsupported arch for Arch build

- build-vm-kvm
disabled in sle/leap host kernel anyway, see also boo#1206618
> add cap-htm=off on power9

- build-recipe-kiwi
user:group are to be separeted by `:`, not `.`
Fixes a warning like
```
[ 1233s] running product builder...
[ 1233s] chown: warning: '.' should be ':': 'abuild.abuild'
```
> Use correct syntax for chown

- Build/IntrospectGolang.pm
- generate_sbom
Before:
```
trivy sbom --format template --template '{{ $vuln := 0 }}{{- range . }}{{- range .Vulnerabilities }}{{- $vuln = add $vuln 1 }}{{- end -}}{{- end -}}Vuln count: {{ $vuln }}'  /home/scc/code/obs-build/obs-sbom.spdx.json
2024-11-18T17:50:14+01:00       INFO    [vuln] Vulnerability scanning is enabled
2024-11-18T17:50:15+01:00       INFO    Detected SBOM format    format="spdx-json"
2024-11-18T17:50:18+01:00       WARN    [sbom] Ignore the OS package as no OS is detected.      file_path="/home/scc/code/obs-build/obs-sbom.spdx.json"
2024-11-18T17:50:18+01:00       INFO    Number of language-specific files       num=1
2024-11-18T17:50:18+01:00       INFO    [gobinary] Detecting vulnerabilities...
2024-11-18T17:50:18+01:00       WARN    Version matching error  err="version error …
```
> Make spdx SBOMs readable by trivy scanner

- changelog2spec
Without this change, parsing changelog entries such as `Tue Mar 28 07:25:39 WEST 2017 - someone@suse` (from `yast2.changes`)
would produce a `Mar 27` date in the .spec file, because
```bash
TZ=CET perl -e 'use Date::Parse; print str2time("28 Mar 2017")'
1490652000
```
considers the local timezone and maps to
```bash
date -d @1490652000 -u -Iseconds
2017-03-27T22:00:00+00:00
```
This patch was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).
> Parse unknown timezones as UTC

- build-pkg-deb
This is wanted to inject eg 64bit kernel package on a 32bit system.
> debian: Ignoring package architecture like we do with rpm

- Build.pm
- build-recipe-mkosi
The package itself can pull in what it needs. The list of dependencies changes too often to be hard-coded here.
Also allow storing recipes in git via obs_scm.
> mkosi: drop most systemd/build-packages deps and use obs_scm directory as source if present

- build-recipe-mkosi
In https://github.com/systemd/mkosi/pull/3507 we've made a slight change to the command line parser to remove ambiguity. This requires all boolean options to receive an explicit argument now. This commit changes OBS to pass all boolean options with an argument. This was already supported by mkosi and will still work even with older versions of mkosi so the change should be safe to make.
> mkosi: Pass --checksum=yes instead of --checksum

- Build/Docker.pm
- obs-docker-support
- t/parse_docker.t
Allow wget calls to be cached by download_assets.
Sample Dockerfile for testing:
```Dockerfile
#!UseOBSRepositories
#!ExclusiveArch: x86_64 aarch64
#!BuildTag: tumbleweed-logo
FROM opensuse/tumbleweed
RUN zypper in -y wget
RUN wget -O /root/opensuse-icon.svg https://static.opensuse.org/favicon.svg
RUN wget https://static.opensuse.org/favicon.svg
RUN curl -o /root/die-logo.svg https://linux.die.net/style/logo.svg
```
> Add support for 'wget' in Docker images

- Build.pm
The previous commit was a bit too zealous in dropping system-packages. Add back those that are used directly by the obs-build build-recipe-mkosi as the mkosi packages in the distros won't necessarily use them and thus depend on them directly.
Follow-up for 69e46e72f4be385bd428e4656b04a70395ad73ea
> mkosi: add back system-packages used by build-recipe directly
