build-vm-kvm

Avoid relying on QEMU's auto disk detection.

Fix guest escaping disk vulnerability in KVM workers

---

Build.pm
Build/Collax.pm
Build/Deb.pm
build
build-recipe
build-recipe-collax
build.1
configs/collax.conf

This also requires changes to bs_srcserver to recognize build.collax files as recipes, and Type: collax in the prjconf. Unfortunatley, I do not know where.

Collax support

---

build-vm
expanddeps

I want to reslove https://github.com/openSUSE/obs-build/issues/216
if you have any comment, tell me please

vminstall are in expanded package list

---

build-recipe-kiwi

Add support for the new kiwi v8 code base

Support new kiwi

---

build
build-vm
build-vm-kvm

to reduce the impact of people's untrusted code breaking out of kvm
In order to do this, we give access to all necessary files.

add --vm-user option to run kvm as non-root

---

build-vm-kvm

also use getent instead of reading passwd directly
to allow NIS/LDAP users

use qemu user for KVM builds by default

---

build-vm-pvm

Signed-off-by: Dinar Valeev <dvaleev@suse.com>

PVM: fix closeconsole

---

Build/Deb.pm

Support Build-Depends such as the following:
g++-multilib [amd64 armel armhf i386 kfreebsd-amd64 mips mips64 mips64el mipsel mipsn32 mipsn32el powerpc ppc64 s390 s390x sparc sparc64 x32] <!cross>
g++-5-x86-64-linux-gnu [amd64] <cross>
binutils:native (>= 2.25.90) | binutils-multiarch:native (>= 2.25.90)
We just ignore :native, as with :any, but pay attention to the build
profile formulae.  We simply use an empty build profile set for now,
which works appropriately with <cross>, <!cross>, <stage1>, <!stage1>,
etc.
This fixes issue #250
Signed-off-by: Bob Ham <bob.ham@collabora.com>

Build: Add support for :native arch specifiers and build profiles

---

build-vm-lxc

This is a minor patch to make build recognise new LXC version.

Add support for building with LXC version 2.

---

Build/Rpm.pm

This is needed by https://github.com/openSUSE/obs-service-source_validator/pull/39

Consider the "Icon" tag in Rpm::parse

---

build-recipe-kiwi
build-vm-docker

Signed-off-by: Dinar Valeev <k0da@opensuse.org>

Setup loop devices in docker required for KIWI

---

build-recipe-kiwi

fixed iterator variable imagetype -> imgtype

---

build-vm

follow-up for 8af7d53476fa3d812066e037d419375fa280464d in PR #326

allow to pass custom options via CLI args

---

Build/LiveBuild.pm
build-recipe-livebuild

Signed-off-by: Jan Blunck <jblunck@infradead.org>

Explicitly add Brocade copyright message

---

changelog2spec

needs https://github.com/rpm-software-management/rpm/commit/57f94a582602f0353cdb17a02dc12c4461d4f32d
which already is in openSUSE:Factory
but we make it an option, because we might want to build packages
for older distributions

support full timestamps in rpm changelog

---

configs/arch.conf

https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/curl&id=c6005e4b56d2418858144008f2c88876af41c5c3

add new dependency libnghttp2 for curl

---

debtransform

See individual commits messages for more details

debtransform: use + for release version suffix, append to Debian release for non-native packages, add SHA1 and SHA256 to .dsc

---

Build.pm
Build/Fissile.pm
fissile_example_spec.yml

This is a WIP. We need the first 2 commits to be deployed in order to work on the build-recipe file.

Create fissile package type

---

build-recipe
build-recipe-fissile

Missing:
- Setup the artifacts directory
- Generate a containerinfo file (syntax should change)

[WIP] Create build-recipe-fissile file

---

computeblocklists
extractbuild

Remove useless stat call and fix typo.

Minor cleanups

---

configs/sl15.0.conf
configs/sle15.0.conf

Remove pam-modules from configs

---

configs/arch.conf

https://lists.archlinux.org/pipermail/arch-dev-public/2018-May/029252.html

[archlinux] replace pkg-config with pkgconf

---

configs/debian-jessie.conf
configs/debian-unstable.conf

Add configuration for Debian Unstable and Jessie.
Author: Héctor Orón Martínez <zumbi@debian.org>
Signed-off-by: Andrew Lee (李健秋) <ajqlee@debian.org>

Adds Debian configurations

---

build-vm-kvm

separate cpu flags to extra variable
set power9 as compat to power8 for now

build-vm-kvm: separate cpu flags to extra variable, set power9 as

---

build-vm-kvm

build-vm-kvm: move serial option from drive to device to work with current qemu

---

configs/sl15.5.conf

Needed for https://build.opensuse.org/request/show/664074 - libreadline7 is going to disappear

Prepare for libreadline8 coming to Tumbleweed

---

build
init_buildsystem

Export SYSTEMD_OFFLINE=1 to avoid failures from systemctl

---

vc

If content is given there is also no need to open the editor.

Do not open the editor if content is set

---

build-recipe-arch
configs/arch.conf

- PKGBUILDS now generate a src.tar.gz package
- arch.conf has a Prefer: iptables to satiate dependency solver

Arch Improvements

---

build

we have constraints meanwhile in OBS

do not retry automatically on disk full

---

build

use abuild user if $NOROOTFORBUILD is set.

---

Build/Kiwi.pm
build-recipe-kiwi

To pre-define milestone names also for appliances

support OBS-Milestone comment for kiwi

---

configs/sl15.5.conf

This is independend if the decision what we use in OBS.

Factory preinstall using dep expansion

---

build
build-vm

This allows better storage with slight overhead. Also reduces the
final archive size.

enable compression on ccache

---

build-vm-kvm
build-vm-qemu

* allow qemu mode to use virtio-serial (works with current ppc kernel, but not aarch64)
* allow sysrq sending with virtio console

further fixes for console handling

---

build-vm

Also cleaning up buildroot after converting content into the image

get virt-make-fs working without --clean

---

build

build: also export the variables BUILD_USER

---

Build/Rpm.pm
spectool

Autonumber

---

Build.pm
Build/Flatpak.pm
build-recipe
build-recipe-flatpak
call-flatpak-builder
init_buildsystem
t/data/flatpak.json
t/data/flatpak.yaml
t/flatpak.t

Here are several packages I were able to sucessfuly build:
https://build.opensuse.org/project/show/home:tinita:flatpak
The file must be called `flatpak.yaml`, `flatpak.json`, `flatpak.json`

Add flatpak support

---

README.md

* Add link to latest builds
* Fix typos

More README.md edits

---

build-vm-kvm

hopefully bsc#1163684 is fixed

drop option transparent_hugepages=never on s390x

---

README.md

https://software.opensuse.org/download/package?package=obs-build&project=openSUSE%3ATools give info how to install from those repos,

Link to downloads page with instructions

---

build
build-vm

To avoid to call build --shell manually as fallback

add --shell-after-fail option for local build

---

PBuild/Preset.pm
pbuild

also list exisiting presets when no default exists and none was choosen.

pbuild: allow to defined a default preset

---

build-recipe-simpleimage

fixes https://github.com/openSUSE/obs-build/issues/709

build-recipe-simpleimage: Fix SRCDIR usage

---

Build/Docker.pm

To give OBS a hint not to build for certain architectures

Dockerfile: support ExcludeArch and ExclusiveArch tags

---

build-vm
build-vm-kvm
build-vm-qemu
build-vm-uml
build-vm-xen

We'd like to have guest kernels which oops panic quickly
rather than hanging for hours and trying to recover..

set oops=panic in all cases

---

build
build-vm
common_functions
init_buildsystem

Fixing building as user with kvm

Fix build as user

---

build-vm
docs/cross_arch_build.adoc

this caused the CI jobs to fail

remove trailing whitespace

---

extractbuild

qcow2 is an entirely different image format.

extractbuild: it is qcow2

---

build

It tried to jump into chroot instead

fix --shell --noinit combination with --vm-type

---

build-vm
call-podman
startdockerd

We still might to have lo network if initrd took take care, like
it does on our current distros

Neither /sbin/ip nor /sbin/ifconfig might be installed

---

Build.pm
build-recipe-mkosi

mkosi: shellcheck clean, add apt for deb builds

---

generate_spdx_sbom

Construct the purl namespace based on the rpm vendor tag
Adding an option to manual set distro flag

initial code for SPDX product data

---

build
build-recipe
build-recipe-spec

build: add '--recipe-opt=OPTIONS' to pass generator options

---

init_buildsystem

Fixes [Bug 1205376](https://bugzilla.opensuse.org/show_bug.cgi?id=1205376)

Clean-up interaction: adapt to line buffering

---

build-vm
build-vm-podman

Experimental backend to allow building packages with a (potentially rootless) podman as a runner.

Add podman vm build type

---

build-vm

A misnamed variable prevented the tunefs parameter being applied.

fix tunefs functionality

---

Build/Rpm.pm

Fixes: 175ea221911b95a515c8c051d3b0346936331e07

Use the lowercased tag for storing the value

---

Build/Docker.pm
Build/Kiwi.pm
Build/Rpm.pm

Supported in spec, kiwi and Dockerfile

Support parsing of bcntsynctag from sources

---

build-recipe-docker
queryconfig

To support for example spaces via %20
Alternative implementation for pull request 965

docker: decode ascii encoded dockerarg strings

---

Build/Rpm.pm

Support %bcond of rpm 4.17.1

---

Build/Mkosi.pm

InitrdPackages= was added somewhat recently for packages that are specific to initrd images. Parse and pull those as well.

mkosi: also fetch InitrdPackages= dependencies

---

Build/ProductCompose.pm

Allowing overwriting the default packagesets per flavor.
Small behaviour change following product-composer: The 'unpack' named packageset is not implicit used, it needs to be listed explicit in the unpack packageset array.

productcomposer: support content and unpack per flavor
